# Generated by Django 4.1.7 on 2023-04-23 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.CharField(max_length=64, unique=True)),
                ('province_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrorail.provinces')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_code', models.CharField(max_length=3)),
                ('regions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrorail.regions')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=4)),
                ('direction', models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN')], max_length=4)),
                ('day_of_week', models.CharField(choices=[('WK', 'WEEKDAY'), ('SUN', 'SUNDAY'), ('SAT', 'SATURDAY')], max_length=3)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrorail.route')),
                ('stations', models.ManyToManyField(through='metrorail.ArrivalTime', to='metrorail.station')),
            ],
        ),
        migrations.AddField(
            model_name='arrivaltime',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrorail.station'),
        ),
        migrations.AddField(
            model_name='arrivaltime',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrorail.train'),
        ),
    ]
